name: "Test"

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v1

      - name: Build
        working-directory: SAT2
        run: |
          make

      - name: Unit tests
        working-directory: SAT2
        run: build/test
