name: "Test"

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Get-Cmake
        uses: lukka/get-cmake@latest

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        
      - name: Installing Dependencies
        run:   |
         sudo apt update
        shell: bash

      - name: Build
        working-directory: SAT2
        run: |
          make

      - name: Unit tests
        working-directory: SAT2
        run: build/test
